language: node_js
os:
  - linux
cache:
  yarn: true
  directories:
    - ~/.npm
before_install:
  - yarn --dev add codecov.io coveralls
notifications:
  email: false
node_js:
  - '10'
script:
  - yarn lint
  - yarn test
  - yarn build
matrix:
  allow_failures: []
  fast_finish: true
jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
    - master
    - next
    - gh-pages
